// hospitals.js
// 30 phổ biến, tên tiếng Việt, địa chỉ quen thuộc (dùng seed trực tiếp)
const hospitals = [
    {
        name: "Viện Huyết học – Truyền máu Trung ương",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "Số 5 Phạm Văn Bạch, phường Yên Hòa, quận Cầu Giấy, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Truyền máu – Huyết học TP. Hồ Chí Minh",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "118 Hồng Bàng, phường 12, quận 5, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Chợ Rẫy",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "201B Nguyễn Chí Thanh, phường 12, quận 5, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Bạch Mai",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "78 Giải Phóng, phường Phương Mai, quận Đống Đa, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Hữu nghị Việt Đức",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "40 Tràng Thi, quận Hoàn Kiếm, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Trung ương Quân đội 108",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "Số 1 Trần Hưng Đạo, quận Hai Bà Trưng, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Quân y 103",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "261 Phùng Hưng, phường Phúc La, quận Hà Đông, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện E Trung ương",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "87-89 Trần Cung, phường Nghĩa Tân, quận Cầu Giấy, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Nhi Trung ương",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "18/879 La Thành, phường Láng Thượng, quận Đống Đa, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Phụ sản Trung ương",
        city: "Hà Nội",
        region: "Hà Nội",
        address: "43 Tràng Thi, quận Hoàn Kiếm, Hà Nội",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Trung ương Huế",
        city: "Huế",
        region: "Thừa Thiên Huế",
        address: "16 Lê Lợi, thành phố Huế, Thừa Thiên Huế",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đà Nẵng",
        city: "Đà Nẵng",
        region: "Đà Nẵng",
        address: "124 Hải Phòng, quận Hải Châu, Đà Nẵng",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Nhân dân 115",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "527 Sư Vạn Hạnh, phường 12, quận 10, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Nhân dân Gia Định",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "01 Nơ Trang Long, phường 7, quận Bình Thạnh, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đại học Y Dược TP. Hồ Chí Minh",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "215 Hồng Bàng, phường 11, quận 5, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Từ Dũ",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "284 Cống Quỳnh, phường Phạm Ngũ Lão, quận 1, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Hùng Vương",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "128 Hồng Bàng, phường 12, quận 5, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Nhi Đồng 1",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "341 Sư Vạn Hạnh, phường 10, quận 10, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Nhi Đồng 2",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "14 Lý Tự Trọng, phường Bến Nghé, quận 1, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Thống Nhất",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "1 Lý Thường Kiệt, phường 7, quận Tân Bình, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Trưng Vương",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "266 Lý Thường Kiệt, phường 14, quận 10, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Bệnh Nhiệt đới TP. Hồ Chí Minh",
        city: "TP. Hồ Chí Minh",
        region: "TP. Hồ Chí Minh",
        address: "764 Võ Văn Kiệt, phường 1, quận 5, TP. Hồ Chí Minh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Việt – Thụy Điển Uông Bí",
        city: "Uông Bí",
        region: "Quảng Ninh",
        address: "Đường Quang Trung, phường Thanh Sơn, TP. Uông Bí, Quảng Ninh",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Hữu nghị Việt Tiệp",
        city: "Hải Phòng",
        region: "Hải Phòng",
        address: "Số 1 Nhà Thờ, phường Lạc Viên, quận Ngô Quyền, Hải Phòng",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa Quảng Ninh",
        city: "Hạ Long",
        region: "Quảng Ninh",
        address: "Bệnh viện đa khoa tỉnh Quảng Ninh, phường Đại Yên, Hạ Long",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa tỉnh Khánh Hòa",
        city: "Nha Trang",
        region: "Khánh Hòa",
        address: "19 Yersin, phường Lộc Thọ, TP. Nha Trang, Khánh Hòa",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa Đồng Nai",
        city: "Biên Hòa",
        region: "Đồng Nai",
        address: "Số 2 đường Đồng Khởi, phường Tam Hòa, TP. Biên Hòa, Đồng Nai",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa Bình Dương",
        city: "Thủ Dầu Một",
        region: "Bình Dương",
        address:
            "5 Phạm Ngọc Thạch, phường Hiệp Thành, TP. Thủ Dầu Một, Bình Dương",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa Trung ương Cần Thơ",
        city: "Cần Thơ",
        region: "Cần Thơ",
        address: "315 Nguyễn Văn Linh, quận Ninh Kiều, TP. Cần Thơ",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa tỉnh Nghệ An",
        city: "Vinh",
        region: "Nghệ An",
        address: "17 Nguyễn Phong Sắc, TP. Vinh, Nghệ An",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa tỉnh Thanh Hóa",
        city: "Thanh Hóa",
        region: "Thanh Hóa",
        address: "181 Hải Thượng Lãn Ông, phường Đông Vệ, TP. Thanh Hóa",
        contact: { phone: "", email: "" },
    },
    {
        name: "Bệnh viện Đa khoa tỉnh Quảng Ngãi",
        city: "Quảng Ngãi",
        region: "Quảng Ngãi",
        address: "60 Nguyễn Nghiêm, phường Nguyễn Nghiêm, TP. Quảng Ngãi",
        contact: { phone: "", email: "" },
    },
];

export default hospitals;
